ubuntu:
	multistrap -a arm64 -d ubuntu_rootfs -f config.ubuntu

debian:
	multistrap -a arm64 -d debian_rootfs -f config.debian

ubuntu32:
	multistrap -a armhf -d ubuntu_rootfs32 -f config.ubuntu

debian32:
	multistrap -a armhf -d debian_rootfs32 -f config.debian


.PHONY: ubuntu debian ubuntu32 debian32



