obj-y+=tensor_mem.o
obj-y+=graph_optimizer.o
obj-y+=dev_executor.o
obj-y+=dev_allocator.o
obj-y+=dev_scheduler.o
obj-y+=generic_dev_executor.o
obj-y+=graph_task.o
obj-y+=device_driver.o
obj-y+=cpu_driver.o
obj-y+=soc_runner.o
obj-y+=node_ops.o
obj-y+=arm64_registry.o

CXXFLAGS+=-O2
