obj-y+=tensor_mem.o
obj-y+=graph_optimizer.o
obj-y+=dev_executor.o
obj-y+=dev_allocator.o
obj-y+=dev_scheduler.o
obj-y+=generic_dev_executor.o
obj-y+=graph_task.o
obj-y+=device_driver.o
obj-y+=node_dev_executor.o
obj-y+=node_dev_driver.o
obj-y+=node_ops.o
obj-y+=tengine_test_api.o
obj-y+=cpu_info.o
obj-y+=custom_kernel.o

COMMON_CFLAGS+=-I../../driver/cpu
