obj - y += acl_driver.o obj - y += acl_conv.o obj - y += acl_lrn.o

                                                             CXXFLAGS +=
    -I.

     acl_driver_CXXFLAGS += -I$(ACL_ROOT) - I$(ACL_ROOT) / include -
                            I$(ACL_ROOT) / utils acl_conv_CXXFLAGS +=
    -I$(ACL_ROOT) - I$(ACL_ROOT) / include -
    I$(ACL_ROOT) / utils acl_lrn_CXXFLAGS +=
    -I$(ACL_ROOT) - I$(ACL_ROOT) / include - I$(ACL_ROOT) / utils
