obj-y+=conv_2d_dw.o
obj-y+=conv_2d_fast.o
obj-y+=sgemm_4x16_interleave.o
obj-y+=sgemm_4x4_interleave.o
obj-y+=sgemm_4x16_interleave_relu_fused.o
obj-y+=sgemm_4x4_interleave_relu_fused.o
obj-y+=dw_k3s1p1.o
obj-y+=dw_k3s2p1.o
obj-y+=dw_k3s1p1_relu_fused.o
obj-y+=dw_k3s2p1_relu_fused.o


