obj-y+=init.o
obj-y+=ref_convolution.o
obj-y+=ref_pooling.o
obj-y+=ref_deconvolution.o
obj-y+=ref_fully_connected.o
obj-y+=ref_softmax.o
obj-y+=ref_concat.o
obj-y+=ref_permute.o
obj-y+=ref_swap_axis.o
obj-y+=ref_rpn.o
obj-y+=prelu.o
obj-y+=relu.o
obj-y+=relu6.o
obj-y+=sigmoid.o
obj-y+=squeeze.o
obj-y+=tanh.o
obj-y+=resize.o
obj-y+=reshape.o
obj-y+=flatten.o
obj-y+=dropout.o
obj-y+=ref_detection_postprocess.o
obj-y+=ref_lrn.o
obj-y+=eltwise.o
obj-y+=ref_slice.o
obj-y+=split.o
obj-y+=pad.o
obj-y+=reduction.o
obj-y+=ref_add_n.o
obj-y+=ref_batchnorm.o
obj-y+=ref_normalize.o

COMMON_CFLAGS+=-I.


