obj-y+=basesocket.o
obj-y+=clientsocket.o
obj-y+=md5.o
obj-y+=thread.o
obj-y+=onlinereportfmtdat.o
obj-y+=onlinereportmgr.o
obj-y+=reportbasedata.o
obj-y+=reportdata.o
obj-y+=onlinereportutil.o
obj-y+=tenginereportmgr.o

COMMON_CFLAGS+=-DENABLE_ONLINE_REPORT
