obj-y+=concat.o
obj-y+=dropout.o
obj-y+=softmax.o
obj-y+=lrn.o
obj-y+=eltwise.o
obj-y+=slice.o
obj-y+=normalize.o
obj-y+=permute.o
obj-y+=flatten.o
obj-y+=priorbox.o
obj-y+=reshape.o
obj-y+=detection_output.o
obj-y+=prelu.o
obj-y+=region.o
obj-y+=reorg.o
obj-y+=rpn.o
obj-y+=roi_pooling.o
obj-y+=relu6.o
obj-y+=relu.o
obj-y+=resize.o
obj-y+=pooling.o
obj-y+=batchnorm.o
obj-y+=scale.o
obj-y+=logistic.o
obj-y+=detection_postprocess.o
obj-y+=stridedslice.o
obj-y+=pad.o
obj-y+=upsample.o
obj-y+=crop.o
obj-y+=l2normalization.o
obj-y+=l2pool.o
obj-y+=elu.o
obj-y+=layernormlstm.o
obj-y+=relu1.o

obj-y+=fused/
obj-y+=init.o

obj-y+=copy.o
obj-y+=power.o
obj-y+=feature_match.o


obj-$(CONFIG_ARCH_BLAS)+=blas/

obj-$(CONFIG_ARCH_ARM32)+=lrn_arm.o
obj-$(CONFIG_ARCH_ARM64)+=lrn_arm.o
