obj-y+=acl_graph_driver.o
obj-y+=acl_graph_device.o
obj-y+=acl_graph_executor.o

CXXFLAGS+=-I. 


acl_graph_driver_CXXFLAGS+=-I$(ACL_ROOT) -I$(ACL_ROOT)/include -I$(ACL_ROOT)
acl_graph_device_CXXFLAGS+=-I$(ACL_ROOT) -I$(ACL_ROOT)/include -I$(ACL_ROOT)
acl_graph_executor_CXXFLAGS+=-I$(ACL_ROOT) -I$(ACL_ROOT)/include -I$(ACL_ROOT)
