bin-obj-y+=test_any.o
#bin-obj-y+=test_message_bus.o
bin-obj-y+=test_obj_attr.o
bin-obj-y+=test_named_data.o
bin-obj-y+=test_tensor.o
bin-obj-y+=test_parameter.o
# bin-obj-y+=test_base_object.o
bin-obj-y+=test_log.o
bin-obj-y+=test_factory.o
bin-obj-y+=test_vararg.o
bin-obj-y+=test_notify.o


