
ifeq ($(CONFIG_CAFFE_REF),y)
bin-obj-y+=test_convolution.o
bin-obj-y+=test_fc.o
bin-obj-y+=test_pooling.o
bin-obj-y+=test_scale.o
bin-obj-y+=test_batch_norm.o
bin-obj-y+=test_prelu.o
endif

bin-obj-y+=test_demo_op.o


CXXFLAGS+=-I.
