MESSAGE(STATUS "operation system is ${CMAKE_SYSTEM}")

IF (CMAKE_SYSTEM_NAME MATCHES "Linux")
    MESSAGE(STATUS "current platform: Linux ")
ELSEIF (CMAKE_SYSTEM_NAME MATCHES "Windows")
    MESSAGE(STATUS "current platform: Windows")
ELSEIF (CMAKE_SYSTEM_NAME MATCHES "FreeBSD")
    MESSAGE(STATUS "current platform: FreeBSD")
ELSE ()
    MESSAGE(STATUS "other platform: ${CMAKE_SYSTEM_NAME}")
ENDIF (CMAKE_SYSTEM_NAME MATCHES "Linux")

IF (WIN32)
    MESSAGE(STATUS "Now is windows")
ELSEIF (APPLE)
    MESSAGE(STATUS "Now is Apple systems.")
    option(MACOS "compiler undr mac os " ON)
    if(MACOS)
        MESSAGE(STATUS "MAC OS COMPILER")
        add_definitions(-DMACOS)
    endif()
ELSEIF (OHOS)
    MESSAGE(STATUS "Now is Harmony OS")
    add_definitions(-D_OHOS_)
ELSEIF (ANDROID)
    MESSAGE(STATUS "Now is Android")
    add_definitions(-fno-integrated-as)    
ELSEIF (UNIX)
    MESSAGE(STATUS "Now is UNIX-like OS's. Including Apple os x  and CYGwin")
ENDIF ()