name: linux-x64-cpu-tools-convert

on:
  push:
    branches: [tengine-lite]
    paths:
    - '.github/workflows/linux-x64-cpu-tools-convert.yml'
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'source/*'
    - 'source/api/*'
    - 'source/executer/*'
    - 'source/graph/*'
    - 'source/module/*'
    - 'source/operator/*'
    - 'source/optimizer/*'
    - 'source/scheduler/*'
    - 'source/serializer/*'
    - 'source/system/*'
    - 'source/utility/*'
    - 'source/device/cpu/**'
    - 'tests/**'
    - 'tools/convert_tool/**'
  pull_request:
    branches: [tengine-lite]
    paths:
    - '.github/workflows/linux-x64-cpu-tools-convert.yml'
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'source/*'
    - 'source/api/*'
    - 'source/executer/*'
    - 'source/graph/*'
    - 'source/module/*'
    - 'source/operator/*'
    - 'source/optimizer/*'
    - 'source/scheduler/*'
    - 'source/serializer/*'
    - 'source/system/*'
    - 'source/utility/*'
    - 'source/device/cpu/**'
    - 'tests/**'
    - 'tools/convert_tool/**'

jobs:
  linux-x64-cpu-tools-convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/checkout@v2.3.4
      with:
        repository: protocolbuffers/protobuf
        ref: v3.17.3
        path: protobuf
    - name: build, package, and test
      run: |
        docker run --network=host -v $PWD:$PWD -w $PWD --privileged --ipc=host centos:6 $PWD/.github/workflows/build-package-and-test-convert-tools.sh
    - name: update
      run: sudo apt-get update
    - name: depends
      run: sudo apt-get install libopencv-dev
    - name: configure
      run: mkdir build && cd build && cmake -DTENGINE_BUILD_TESTS=ON ..
    - name: build
      run: cmake --build build -j 2          
    - name: test-data
      run: |
        cd build
        wget ftp://219.139.34.182/tengine/ci_test/model_test_convert/onnx_models.zip
        unzip onnx_models.zip
        wget ftp://219.139.34.182/tengine/ci_test/model_test_convert/onnx_models_output.zip
        unzip onnx_models_output.zip
    - name: test-models
      run: |
        chmod +x ./tests/test_onnx_model.sh
        cd build
        ../tests/test_onnx_model.sh ../convert_tool-x86_64.AppImage
