name: linux-armv8-cpu-gcc

on:
  push:
    branches: [tengine-lite]
    paths:
    paths-ignore: 
    - 'doc/**'
    - 'README.md'
    - 'README_EN.md'
  pull_request:
    branches: [tengine-lite]
    paths-ignore: 
    - 'doc/**'
    - 'README.md'
    - 'README_EN.md'

jobs:
  linux-armv8-cpu-gcc:
    runs-on: TensorRT
    steps:
    - uses: actions/checkout@v2.3.4

    - name: configure
      run: mkdir build && cd build && cmake  -DTENGINE_BUILD_TESTS=ON ..
    - name: build
      run: cmake --build build -j 2
    - name: models
      run: |
        cd build
        wget ftp://219.139.34.182/tengine/ci_test/models.zip
        unzip models.zip
        wget ftp://219.139.34.182/tengine/ci_test/arm64_data.zip
        unzip arm64_data.zip
        mv arm64_data data
        wget ftp://219.139.34.182/tengine/ci_test/images.zip
        unzip images.zip
    - name: test
      run: |
        export PATH=$GITHUB_WORKSPACE/qemu-install/bin:$PATH
        chmod +x ./tests/test_arm64.sh
        cd build
        ../tests/test_arm64.sh
        